/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sinensia.pruebatec.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the UserPrueba service. Represents a row in the &quot;ricoh_UserPrueba&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.sinensia.pruebatec.model.impl.UserPruebaModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.sinensia.pruebatec.model.impl.UserPruebaImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserPrueba
 * @generated
 */
@ProviderType
public interface UserPruebaModel extends BaseModel<UserPrueba> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user prueba model instance should use the {@link UserPrueba} interface instead.
	 */

	/**
	 * Returns the primary key of this user prueba.
	 *
	 * @return the primary key of this user prueba
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user prueba.
	 *
	 * @param primaryKey the primary key of this user prueba
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this user prueba.
	 *
	 * @return the uuid of this user prueba
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this user prueba.
	 *
	 * @param uuid the uuid of this user prueba
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the user ID of this user prueba.
	 *
	 * @return the user ID of this user prueba
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user prueba.
	 *
	 * @param userId the user ID of this user prueba
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user prueba.
	 *
	 * @return the user uuid of this user prueba
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this user prueba.
	 *
	 * @param userUuid the user uuid of this user prueba
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the name of this user prueba.
	 *
	 * @return the name of this user prueba
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this user prueba.
	 *
	 * @param name the name of this user prueba
	 */
	public void setName(String name);

	/**
	 * Returns the family name of this user prueba.
	 *
	 * @return the family name of this user prueba
	 */
	@AutoEscape
	public String getFamilyName();

	/**
	 * Sets the family name of this user prueba.
	 *
	 * @param familyName the family name of this user prueba
	 */
	public void setFamilyName(String familyName);

	/**
	 * Returns the birth date of this user prueba.
	 *
	 * @return the birth date of this user prueba
	 */
	public Date getBirthDate();

	/**
	 * Sets the birth date of this user prueba.
	 *
	 * @param birthDate the birth date of this user prueba
	 */
	public void setBirthDate(Date birthDate);

	/**
	 * Returns the email of this user prueba.
	 *
	 * @return the email of this user prueba
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this user prueba.
	 *
	 * @param email the email of this user prueba
	 */
	public void setEmail(String email);

	/**
	 * Returns the reg date of this user prueba.
	 *
	 * @return the reg date of this user prueba
	 */
	public Date getRegDate();

	/**
	 * Sets the reg date of this user prueba.
	 *
	 * @param regDate the reg date of this user prueba
	 */
	public void setRegDate(Date regDate);

	@Override
	public UserPrueba cloneWithOriginalValues();

}